### ISSUE TITLE
Buff cancellation is broken

### ISSUE THREAD

**Issue by Dicebar** [Dicebar/raven#1]
Right mouse button clicks don't cancel buffs at the moment.

The `TemporaryEnchantFrame` was related to the 'hide blizzard buffs' option not working in fd8eb162b045c37e36bc052950ff5aacd20d378c, which might be related. I'm not sure if the frame no longer exists or if access is more strictly moderated through secure hooks.

**Comment by Aur0r4** [comment]
It's not working with In-Combat-Bar too.

**Comment by dorana** [comment]
I'm currently doing some rework on the buff canceling, using a different solution. Hoping to have this resolved soon

**Comment by Dicebar** [comment]
Awesome, thank you!
