### ISSUE TITLE
Raven not working on WotLK

### ISSUE THREAD

**Issue by Dicebar** [Dicebar/Raven#10]
TheRealSupremacy on CurseForge wrote:

> A few days into the prepatch the addon stops working. Even tho it worked on the beta, PTR and as I said it worked when the prepatch hit.
> 
> So what happened ? Is there a fix coming please ?

GalaticBhalu on CurseForge wrote:
> Had exactly the same problem here, a minor update 3.4.0.xxxxx was deployed and it stopped working, like other addons with it

@dorana wrote:
>Hello, sorry for the late reply, Raven has been low on updates lately and is in the middle of being maintained by Dicebar and myself.
>Currently all the efforts are being put into supporting the new UI systems of the Dragonflight expansion, but we will get into the Classic versions shortly.
>
>Again sorry for putting the classic players on a low priority here, but we have limited development time and a lot to fix.

**Comment by Dicebar** [comment]
@dorana Did we ever fix this?

**Comment by 10leej** [comment]
Addon seems to be operating fine on wrath classic
