### ISSUE TITLE
Doesn't work with Lua Error

### ISSUE THREAD

**Issue by zzipsa22** [Dicebar/raven#14]
4x Interface/AddOns/Raven/Nest.lua:462: bad argument #1 to 'SetTarget' (Usage: local success = self:SetTarget(target))
[string "=[C]"]: in function `SetTarget'
[string "@Interface/AddOns/Raven/Nest.lua"]:462: in function <Interface/AddOns/Raven/Nest.lua:429>
[string "@Interface/AddOns/Raven/Nest.lua"]:2044: in function <Interface/AddOns/Raven/Nest.lua:2014>
[string "@Interface/AddOns/Raven/Nest.lua"]:2703: in function `Nest_Update'
[string "@Interface/AddOns/Raven/Main.lua"]:1222: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:897: in function <Interface/AddOns/Raven/Main.lua:893>

Locals:
(*temporary) = Alpha {
 0 = <userdata>
}
(*temporary) = "Raven_Animation1_Spark1"

It pops up at first login, and raven just doesn't work.  (can't see buff frame at all)
I changed options but nothing happened with no more error.

BTW Thank you for maintaining this great addon :D

**Comment by dorana** [comment]
Thank you, we have had other reports about the sparkle effect causing errors, third of likely related to this

**Comment by Dicebar** [comment]
This bug is identical to the bug reported in #6...for which an bugfix will go out shortly 😉
