### ISSUE TITLE
Addon isn't showing on retail

### ISSUE THREAD

**Issue by Reanimatez** [Dicebar/Raven#21]
Ever since the new expansion launched, the add-on hasn't been working for me. It loads in game, I can see all the options and menus, but the actual buffs/debuffs, profiles, etc. that I use the add-on for don't show up. Toggling test mode seems to be broken too, as it doesn't do anything anymore. Issue persists even if I disable all of my other addons, besides this one.

**Comment by Dicebar** [comment]
Sorry for the probably redundant question, but these all sound like problems we have fixed before so I have to ask... Are you sure you're using the latest version of the addon?

Presuming you are, can you try creating a new profile to see if it works like that?

**Comment by Dicebar** [comment]
Also, since I just noticed the option...can you check if under "Setup" Raven is actually enabled?

**Comment by Reanimatez** [comment]
Late reply, but you were right, it wasn't updated to the newest version (it was marked as updated on curseforge, but it actually wasn't using the newest version).  Thanks, I can finally see my buffs again :)

**Comment by Dicebar** [comment]
Awesome, glad to hear it! 🙂
