### ISSUE TITLE
r613 Lua errors and none of my bars and icons show on the screen

### ISSUE THREAD

**Issue by cgage1971** [Dicebar/Raven#25]
After initial login, get this error:

2x Raven/Conditions.lua:432: attempt to call global 'RequiresMinExpansion' (a nil value)
[string "@Raven/Conditions.lua"]:432: in function `CheckSpec'
[string "@Raven/Bars.lua"]:1891: in function <Raven/Bars.lua:1876>
[string "@Raven/Bars.lua"]:1899: in function <Raven/Bars.lua:1898>
[string "@Raven/Bars.lua"]:2146: in function `UpdateBars'
[string "@Raven/Main.lua"]:1258: in function `Update'
[string "@Raven/Main.lua"]:924: in function <Raven/Main.lua:920>
[string "@Raven/Main.lua"]:955: in function `?'

When right clicking icon to show icons and progress bars, get this error:

2x AceLocale-3.0-6: Raven: Missing entry for 'Include Cobal Cooldown'
[string "@Raven_Options/Options.lua"]:7657: in main chunk
[string "=[C]"]: in function `LoadAddOn'
[string "@Raven/Main.lua"]:1100: in function `OptionsPanel'
[string "@Raven/Main.lua"]:1164: in function `OnClick'
[string "@BugSack/Libs/LibDBIcon-1.0-45/LibDBIcon-1.0.lua"]:144: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

**Comment by Dicebar** [comment]
Thanks for the report!

Both of these bugs should be fixed in the latest version (r615 and above).
