### ISSUE TITLE
[Request] Upload versions to WoW Interface (and/or Github)

### ISSUE THREAD

**Issue by Gethe** [Dicebar/Raven#26]
Raven was previously also maintained on WoW Interface and I would like the request for this the continue. The admin there [Cairenn](https://www.wowinterface.com/forums/member.php?find=lastposter&f=26), is very helpful and will likely be more than happy to grant access to the [existing addon page](https://www.wowinterface.com/downloads/info18242-Raven.html).

The [community packager](https://github.com/BigWigsMods/packager) uses the same pkgmeta format that curse does, so you wouldn't require much setup. This packager can also create and upload releases on Github as well.

**Comment by Dicebar** [comment]
Hi @Gethe! That sounds like an awesome idea. I'll try to set that up today or tomorrow.

**Comment by Tojaso** [comment]
I am happy to work with you to get access to wowinterface Raven page. Let me know your forum name on taht site and I should be able to add you.

**Comment by Dicebar** [comment]
@Tojaso Thanks mate! I sent you a message on Discord.

**Comment by Dicebar** [comment]
A small update for @Gethe. We're intending to support WowInterface, but this will require some extra software to be written for it to fit properly into our development pipeline. So it's on our to-do list, but it's going to be a few weeks before we get to it.

For the intermediate period, I have submitted r616 manually to the website, pending moderator approval.

**Comment by Gethe** [comment]
Awesome thanks!

**Comment by Dicebar** [comment]
Raven should now be updated automatically on WowInterface whenever we make a release 🥳
