### ISSUE TITLE
Spell Ready condition not working for certain spells

### ISSUE THREAD

**Issue by cgage1971** [Dicebar/Raven#29]
On my warrior, I'm trying to set up spell conditions to show when Whirlwind and Slam are ready. No matter what, the condition always shows true, even when the spell is on cooldown. (See attached image with the slam spell). Other spell conditions work, like Rampage, Bloodthirst, etc. Not sure if this is a Blizzard issue or Raven. 

![image](https://user-images.githubusercontent.com/117052076/210898829-bc0f4309-b691-48af-95ae-0bee1ca97197.png)

**Comment by Dicebar** [comment]
Hey @cgage1971 , sorry for the late response. I have been overwhelmed with IRL work.

How do you get a cooldown on Slam? I haven't play warrior in a while since Shadowlands, and I couldn't immediately find a talent that adds a cooldown.

**Comment by cgage1971** [comment]
No worries. Thanks for taking this addon over. The talent that makes Slam and Whirlwind have cooldowns is Storm of Swords (2nd from bottom on the left side of the tree)
![ABD38FB3-C89D-4F5C-8323-A712640D0B3A](https://user-images.githubusercontent.com/117052076/212457468-6e27f723-e8fa-466b-bed5-afb55ac7ff2a.jpeg)

**Comment by Dicebar** [comment]
Thanks for the extra info. I was totally looking under Arms talents 🤦‍♂️

Raven tries to be efficient when tracking cooldowns, and by default it ignores abilities that are normally on the GCD. I added an exception for Slam which should fix this issue. The update should be available soon™️ on CurseForge.

Note to self/@dorana: This may be relevant for other talents that add cooldowns to abilities that are normally on the GCD as well. `GetSpellBaseCooldown` gives us the cooldown _before_ talents are applied (GCD for Slam). `GetSpellCooldown` gives us the the _current_ cooldown (read: 0 when loading into the game). So neither are useful for building the cooldown cache when it comes to talents like these. If these types of talents become more common we may need to rewrite/extend the caching code.

**Comment by cgage1971** [comment]
Thanks!
