### ISSUE TITLE
Icon Bars not saving Positions

### ISSUE THREAD

**Issue by Dicebar** [Dicebar/Raven#3]
@Galthariel reported that icon bars are not maintaining position between load screens, even though the correct positions appear to be preserved in backup profiles.

See the [original ticket](https://github.com/Dicebar/raven-old/issues/17) for more info.

**Comment by Galthariel** [comment]
You asked me to test when Raven is the only addon enabled and I'll test it for you...the only problem is that the issue is intermittent and may not happen or takes a lot of time and testing but will do my best to try help.

**Comment by Galthariel** [comment]
and I small correction...it seems isn't only the Icon Bars...a few settings also

**Comment by Galthariel** [comment]
and I small correction...it seems isn't only the Icon Bars...a few settings also

**Comment by Dicebar** [comment]
As a note for us maintainers... This could be related to an old issue (Dec '20) over on CurseForge:
https://www.curseforge.com/wow/addons/raven/issues/408

**Comment by Galthariel** [comment]
While isn't exactly the same issue it could be related.

https://www.curseforge.com/wow/addons/raven/issues/408

I will try the fix they used which is to attach the Icon Bar to the UIParent and see if fixes

**Comment by Galthariel** [comment]
Was like this before

![2022-11-09_23-05-29](https://user-images.githubusercontent.com/51491805/201783211-dc691108-82d7-46c4-bd3e-1f0378e6179d.png)

And now is like this

![2022-11-14_19-42-22](https://user-images.githubusercontent.com/51491805/201783515-3de9cff6-3350-44ea-b276-ca7943939191.png)

Did that in character A and logged in character B (using exactly the same profile) and now character B isn't showing the Icon Bar with Buffs :-(

**Comment by Galthariel** [comment]
Logged back to character B and same as A...Buffs disappeared

**Comment by dorana** [comment]
We will continue to monitor this,. I observed a similar issue with another addon, in this case a simple /reload would trigger the positions to revert, are the bars resetting by doing a reload or by login out -> in on the same character?

**Comment by Galthariel** [comment]
Both, and now they just disappeared totally. Doesnt'matter if I move the X and Y total to Right and Left can't find them in any way. Even Reset (not a full reset of the profile), but the reset button that is just at the right side of the X, and Y controls.

**Comment by Galthariel** [comment]
I managed to get it back by copying it from another profile.

**Comment by Galthariel** [comment]
What I just did now was literally delete all the saved variables Lua files and try to start from scratch. Lost all the profiles and since I know all the settings I'm trying to see if this is a corrupted profile or something. Created a new profile on the character **A** and name it **Default DF**. Logged into **B** and didn't copy the profile from **A**...Just pick the created **Default DF** profile and loaded it correctly. Did the same with character C and also loaded correctly. Logout from all and came back to see if the Profile was still ok and hadn't lost its settings or position and so far so good. Let's see if the "Not Saving Positions" issue comes back. Last but not least I'm not using the Anchor Solution but normal Display Position unless you tell me otherwise.

I'll keep you posted if at any loading screen the issue happens again

**Comment by Galthariel** [comment]
I hate to release fireworks before the actual time comes but it seems it's solved. Somehow the profiles got corrupted maybe? what is weird is that all the profiles got corrupted which were 4. The old Default plus the other 3 Profiles with the character name and realm. I've been logging out from one to another and going through loading screens and zero issues so far. As a feature suggestion, it will be nice to add an option to export profiles unless there is already one and I couldn't find it or have saved variables for each character

**Comment by Galthariel** [comment]
I would leave the issue open for a couple of days and then closed myself if gets solved indeed and post the solution there.

**Comment by dorana** [comment]
Most likely this was an issue caused by another error, making the raven not saving correctly due to one or more of the bugs during the pre-patch, 
Most likely he bug that caused raven to not function correctly was solved and thus the saving of the profile worked correctly after this step.
