### ISSUE TITLE
Whirlwind (Arms Warrior)

### ISSUE THREAD

**Issue by DakHarding** [Dicebar/Raven#36]
Hey guys, 

I decided to dust off my Arms Warrior in retail and for some reason Whirlwind's 12 second CD is being sporadically ignored when setting it as a condition under 'Spell Ready'. Even tried adding it under 'All Cooldowns', but it's still ignored. It'll cast like normal, but as it's counting down on my hotbar, raven is showing it as being ready to fire off again.

![Whirlwind-Arms](https://user-images.githubusercontent.com/118600255/217731670-ebd41b50-c153-43ef-a4fc-da9f0e89306b.png)

Thanks!

**Comment by DakHarding** [comment]
EDIT: Add Ignore Pain to the list also. The cooldowns appear to only be ignored under the Arms spec where the abilities change, either adding or increasing a cooldown. Whirlwind/Ignore Pain basically have no CD when in Fury/Prot.

**Comment by Dicebar** [comment]
I'm leveling a warrior at the moment. I'll check this out.

**Comment by Dicebar** [comment]
This seems identical to #29, which caused a similar bug for Slam for Fury warriors. It's fixed in the next released.

**Comment by DakHarding** [comment]
Hello again, on retail with Arms Warrior, still running into intermittent issues again with cooldowns showing available while still counting down. Sometimes 4-5 seconds out. Specifically Ignore Pain and Shield Block. 

Also, attached a pic and the following Shield Block conditional doesn't seem to work even though all criteria are true. Thanks.
![ShieldBlockBug](https://user-images.githubusercontent.com/118600255/223919971-eda1356d-b457-4c22-8e18-b5b308caf7f3.png)
