### ISSUE TITLE
Raven r603 unresponsive in 10.0.02 for some users

### ISSUE THREAD

**Issue by Dicebar** [Dicebar/Raven#4]
Various bug reports indicate that Raven is unresponsive on the live servers, without any errors being thrown.

It seems to reflect the same bug Akgis reported on beta, for which he shared a video:
https://www.youtube.com/watch?v=r2fJ7x3K6ek&ab_channel=Akgis

Some bug reports indicate a different problem, with conditions that stop working randomly. This might be related, so I'm including it in this report.

Variables that can be excluded as causes:
- Character race and class
- Localization

**Comment by Crowmeister** [comment]
@Dicebar 
So I have made two videos with my Monk. 

One fighting a normal training dummy and one fighting a Tank training dummy (the ones that fight back). My issues only appears on the Tank training dummy, it MIGHT be because then I get damage to trigger Stagger. I have a Stagger bar with Tooltip number ticked on. 

With the Tank dummy Raven 'freezes'. No errors but the bars and icons dont update anymore.  See videos

Normal dummy, no problem ->  https://youtu.be/TyiL7IMgdU0
Tank dummy, problem -> https://youtu.be/JnRnxWXdG3E

**Comment by dorana** [comment]
thank you for the videos, I will hop onto my monk tank and see if I can replicate the issues

**Comment by Crowmeister** [comment]
Silly of me, there is an error! Check the second video, the moment the bars and icons freeze BugSack registers an error (see ChocolateBar).

10x Interface/AddOns/Raven/Bars.lua:1019: attempt to call method 'SetUnitAura' (a nil value)
[string "@Interface/AddOns/Raven/Bars.lua"]:1019: in function `GetTooltipNumber'
[string "@Interface/AddOns/Raven/Bars.lua"]:1084: in function <Interface/AddOns/Raven/Bars.lua:1067>
[string "@Interface/AddOns/Raven/Bars.lua"]:1917: in function <Interface/AddOns/Raven/Bars.lua:1871>
[string "@Interface/AddOns/Raven/Bars.lua"]:2119: in function `UpdateBars'
[string "@Interface/AddOns/Raven/Main.lua"]:1245: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:911: in function <Interface/AddOns/Raven/Main.lua:907>

Locals:
self = <table> {
 CheckTalent = <function> defined @Interface/AddOns/Raven/Conditions.lua:341
 testOrder = <table> {
 }
 HexColor = <function> defined @Interface/AddOns/Raven/Profile.lua:43
 UpdateInCombatBar = <function> defined @Interface/AddOns/Raven/Cancel.lua:66
 modules = <table> {
 }
 Nest_SetShine = <function> defined @Interface/AddOns/Raven/Nest.lua:1303
 GetValueFormat = <function> defined @Interface/AddOns/Raven/Values.lua:821
 ReleaseBarGroup = <function> defined @Interface/AddOns/Raven/Bars.lua:723
 CopyTable = <function> defined @Interface/AddOns/Raven/Profile.lua:61
 ResetColorDefault = <function> defined @Interface/AddOns/Raven/Profile.lua:424
 Nest_SetBarGroupLock = <function> defined @Interface/AddOns/Raven/Nest.lua:973
 Nest_FormatTime = <function> defined @Interface/AddOns/Raven/Nest.lua:1873
 SetInCombatBar = <function> defined @Interface/AddOns/Raven/Cancel.lua:203
 LocalSpellNames = <table> {
 }
 GetExpireColor = <function> defined @Interface/AddOns/Raven/Profile.lua:641
 UpdateInternalCooldowns = <function> defined @Interface/AddOns/Raven/Main.lua:2063
 SetExpireColor = <function> defined @Interface/AddOns/Raven/Profile.lua:629
 DefaultProfile = <table> {
 }
 ResetColorDefaults = <function> defined @Interface/AddOns/Raven/Profile.lua:443
 RemoveMatchingTrackers = <function> defined @Interface/AddOns/Raven/Main.lua:388
 Nest_CreateBar = <function> defined @Interface/AddOns/Raven/Nest.lua:1074
 CheckSpec = <function> defined @Interface/AddOns/Raven/Conditions.lua:396
 SetEnabledState = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 FinalizeBars = <function> defined @Interface/AddOns/Raven/Bars.lua:161
 mountSpells = <table> {
 }
 Nest_SetLabelColor = <function> defined @Interface/AddOns/Raven/Nest.lua:1279
 LoadCustomBars = <function> defined @Interface/AddOns/Raven/Bars.lua:528
 Nest_DeleteAllBars = <function> defined @Interface/AddOns/Raven/Nest.lua:1243
 Nest_AdjustColor = <function> defined @Interface/AddOns/Raven/Nest.lua:1344
 UpdateTrackers = <function> defined @Interface/AddOns/Raven/Main.lua:1829
 ldbi = <table> {
 }
 Nest_RegisterCallbacks = <function> defined @Interface/AddOns/Raven/Nest.lua:683
 UnregisterAllEvents = <function> defined @Interface/AddOns/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
 InitializeBarGroup = <function> defined @Interface/AddOns/Raven/Bars.lua:494
 Nest_SetBarGroupBorder = <function> defined @Interface/AddOns/Raven/Nest.lua:898
 Nest_GetBarGroups = <function> defined @Interface/AddOns/Raven/Nest.lua:796
 HideBars = <function> defined @Interface/AddOns/Raven/Bars.lua:175
 OptionsPanel = <function> defined @Interface/AddOns/Raven/Main.lua:1084
 Nest_SetBarGroupBackdrop = <function> defined @Interface/AddOns/Raven/Nest.lua:906
 DetectInternalCooldown = <function> defined @Interface/AddOns/Raven/Main.lua:2045
 Nest_SetColors = <function> defined @Interface/AddOns/Raven/Nest.lua:1262
 warlockCreatures = <table> {
 }
 InitializeSpellIDs = <function> defined @Interface/AddOns/Raven/Profile.lua:131
 GetName = <function> defined @Interface/AddOns/Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
 InitializeBuffTooltip = <function> defined @Interface/AddOns/Raven/Main.lua:1424
 professionSpells = <table> {
 }
 ColorPalette = <table> {
 }
 SetConditionDefaults = <function> defined @Interface/AddOns/Raven/Conditions.lua:876
 Nest_SetAlpha = <function> defined @Interface/AddOns/Raven/Nest.lua:1294
 SaveBarGroupSettings = <function> defined @Interface/AddOns/Raven/Bars.lua:525
 Print = <function> defined @Interface/AddOns/Ace3/AceConsole-3.0/AceConsole-3.0.lua:50
 Nest_SetTimeColor = <function> defined @Interface/AddOns/Raven/Nest.lua:1284
 Nest_DeleteBar = <function> defined @Interface/AddOns/Raven/Nest.lua:1179
 UpdateSpellEffects = <function> defined @Interface/AddOns/Raven/Main.lua:1678
 Debug = <function> defined @Interface/AddOns/Raven/Main.lua:195
 Nest_IsTimer = <function> defined @Interface/AddOns/Raven/Nest.lua:1256
 Nest_GetBarGroup = <function> defined @Interface/AddOns/Raven/Nest.lua:793
 Nest_SetTick = <function> defined @Interface/A

**Comment by dorana** [comment]
Thank you this helps a lot.
This is something I missed with the new Namespace handling.
Could you please zip your raven and raven WTF files from 
WOWFOLDER\_retail\WTF\Account\YOURACCOUNT\SavedVariables
folder so that I can use your monk profile as a test platform.

The key word here was when I realized that it had to do with Tooltip, the Tooltip integration with the client is completely reworked.

I will get on this ASAP

**Comment by Crowmeister** [comment]
Sure, here's the addon and my WTF

**Comment by akgis32** [comment]
Hello I had uploaded a video of a draenei shaman, that with my old savedvariables nothing works, here is my raven.lua from savedvariables.

Hope it helps. Any help debuging stuff let me know!

[Raven.zip](https://github.com/Dicebar/Raven/files/10035765/Raven.zip)

**Comment by dorana** [comment]
Issue with the Tooltip causing issues has been solved, sorting new release shortly

**Comment by dorana** [comment]
new version (r604) is up, it should sort Crowmeisters issue, I have not yet tested it with your problems akgis32, I will do so tomorrow morning (EU time)

**Comment by dorana** [comment]
Located issue for akgis32, error was with BarIconText color setting sometimes showing a certain color value as null, sorted by defaulting these to 0

r605 will have this latest fix

**Comment by akgis32** [comment]
hey! Seems to be fixed for the 5mins I had time to play :)

will try more in the evening thanks very much in debugging the issue.

**Comment by dorana** [comment]
Leaving this open over the weekend, or until further results are presented
