### ISSUE TITLE
LUA error on Wrath PTR

### ISSUE THREAD

**Issue by sausje** [Dicebar/Raven#45]
Getting the following error on PTR

> 1x Raven/Main.lua:1033: attempt to call global 'GetContainerItemID' (a nil value)
> [string "@Raven/Main.lua"]:1033: in function `BAG_UPDATE'
> [string "@Raven/Main.lua"]:850: in function <Raven/Main.lua:840>
> [string "=[C]"]: ?
> [string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:61>
> [string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
> [string "@Ace3/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Ace3/AceAddon-3.0/AceAddon-3.0.lua:611>
> 
> Locals:
> self = <table> {
>  CheckTalent = <function> defined @Raven/Conditions.lua:398
>  testOrder = <table> {
>  }
>  HexColor = <function> defined @Raven/Profile.lua:43
>  UpdateInCombatBar = <function> defined @Raven/Cancel.lua:66
>  modules = <table> {
>  }
>  Nest_SetShine = <function> defined @Raven/Nest.lua:1303
>  GetValueFormat = <function> defined @Raven/Values.lua:833
>  ReleaseBarGroup = <function> defined @Raven/Bars.lua:723
>  CopyTable = <function> defined @Raven/Profile.lua:61
>  ResetColorDefault = <function> defined @Raven/Profile.lua:452
>  Nest_SetBarGroupLock = <function> defined @Raven/Nest.lua:973
>  Nest_FormatTime = <function> defined @Raven/Nest.lua:1873
>  SetInCombatBar = <function> defined @Raven/Cancel.lua:203
>  LocalSpellNames = <table> {
>  }
>  GetExpireColor = <function> defined @Raven/Profile.lua:669
>  UpdateInternalCooldowns = <function> defined @Raven/Main.lua:2119
>  SetExpireColor = <function> defined @Raven/Profile.lua:657
>  DefaultProfile = <table> {
>  }
>  ResetColorDefaults = <function> defined @Raven/Profile.lua:471
>  RemoveMatchingTrackers = <function> defined @Raven/Main.lua:401
>  Nest_CreateBar = <function> defined @Raven/Nest.lua:1074
>  CheckSpec = <function> defined @Raven/Conditions.lua:453
>  SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
>  FinalizeBars = <function> defined @Raven/Bars.lua:161
>  mountSpells = <table> {
>  }
>  Nest_SetLabelColor = <function> defined @Raven/Nest.lua:1279
>  LoadCustomBars = <function> defined @Raven/Bars.lua:528
>  Nest_DeleteAllBars = <function> defined @Raven/Nest.lua:1243
>  Nest_AdjustColor = <function> defined @Raven/Nest.lua:1344
>  UpdateTrackers = <function> defined @Raven/Main.lua:1870
>  ldbi = <table> {
>  }
>  Nest_RegisterCallbacks = <function> defined @Raven/Nest.lua:683
>  UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:169
>  InitializeBarGroup = <function> defined @Raven/Bars.lua:494
>  Nest_SetBarGroupBorder = <function> defined @Raven/Nest.lua:898
>  Nest_GetBarGroups = <function> defined @Raven/Nest.lua:796
>  HideBars = <function> defined @Raven/Bars.lua:175
>  OptionsPanel = <function> defined @Raven/Main.lua:1105
>  Nest_SetBarGroupBackdrop = <function> defined @Raven/Nest.lua:906
>  DetectInternalCooldown = <function> defined @Raven/Main.lua:2101
>  Nest_SetColors = <function> defined @Raven/Nest.lua:1262
>  warlockCreatures = <table> {
>  }
>  InitializeSpellIDs = <function> defined @Raven/Profile.lua:141
>  GetName = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:275
>  InitializeBuffTooltip = <function> defined @Raven/Main.lua:1445
>  name = "Raven"
>  ColorPalette = <table> {
>  }
>  SetConditionDefaults = <function> defined @Raven/Conditions.lua:937
>  Nest_SetAlpha = <function> defined @Raven/Nest.lua:1294
>  SaveBarGroupSettings = <function> defined @Raven/Bars.lua:525
>  Print = <function> defined @Ace3/AceConsole-3.0/AceConsole-3.0.lua:50
>  Nest_SetTimeColor = <function> defined @Raven/Nest.lua:1284
>  Nest_DeleteBar = <function> defined @Raven/Nest.lua:1179
>  ExpansionIsOrBelow = <function> defined @Raven/Main.lua:43
>  UpdateSpellEffects = <function> defined @Raven/Main.lua:1718
>  Debug = <function> defined @Raven/Main.lua:206
>  Nest_IsTimer = <function> defined @Raven/Nest.lua:1256
>  Nest_GetBarGroup = <function> defined @Raven/

**Comment by Dicebar** [comment]
Hoi sausje, thanks for the report!

@dorana: Does the PTR count as "main line" for the sake of determining if the API is modern or legacy?

**Comment by sausje** [comment]
> Hoi sausje, thanks for the report!
> 
> @dorana: Does the PTR count as "main line" for the sake of determining if the API is modern or legacy?

Ah apologies, the Wrath PTR

**Comment by dorana** [comment]
Yes it should, but I see that there is a version missmatch, Hold on and I will see if I can adjust

**Comment by Dicebar** [comment]
Thanks!

**Comment by dorana** [comment]
I have pushed r629 this checks for version greater than rather than exact version, PTR moved from 3.4.1 -> 3.4.2 and this caused the PTR to attempt to load the old API again

**Comment by sausje** [comment]
Working flawless now, at least for the purpose that I use it.
