### ISSUE TITLE
bar background opacity slider has no effect

### ISSUE THREAD

**Issue by belatar** [Dicebar/Raven#48]
hi, we chatted on curse comments previously.

for me, the background opacity slider has no effect. i tried using different background textures (including "empty") but no matter where i move the slider, the black background behind bars remains. i am using elvui with s&l and azilrokas addon skins (which doesnt have an entry for raven, so i dont know whether it interacts). thanks for the great addon and your help!

![image](https://github.com/Dicebar/Raven/assets/1206801/350b9784-4a0f-4497-b44e-7a0b1b6b1ec6)

![image](https://github.com/Dicebar/Raven/assets/1206801/ef31134b-513c-4008-99e0-7bc2a5ca7eec)

**Comment by Dicebar** [comment]
Have you tried if the slider works with only Raven enabled?

**Comment by belatar** [comment]
should have thought of that myself, sry.
i tried and it is actually the elvui integration that does this. i disabled it and voila the background disappeared. got everything working now as i want it. thank you!

**Comment by Dicebar** [comment]
No worries, glad you solved it!
