### ISSUE TITLE
background settings dont stick then stop working

### ISSUE THREAD

**Issue by belatar** [Dicebar/Raven#49]
hi, its me again :) (this time i tried with only raven enabled)
so i configured some bar groups and they are working great.
then i wanted to give the groups a 1 pixel colored border. i had previously deactivated all (bar) backgrounds.
i first tried adding a border to a specific group by deactivating defaults.
when first configuring background and border, it worked. but during adjustments to padding, insets etc at some point change didnt do anything anymore. after a reload, settings were lost.
i then tried using „default“ and manipulating default settings, same effect: works at first, then degrades, then stops working entirely.
very weird stuff. any idea what i might be doing wrong?

**Comment by Dicebar** [comment]
Hey hey,

Not entirely sure what's going wrong there. I know adjusting the size of the border can require a `/console reloadui` to work properly, you could give that a shot.

**Comment by belatar** [comment]
thanks again for responding so quickly. i tried around a little and it seems the "edge size" parameter of the background border was the issue.
apparently you cant just set to any (low) value. i assumed i could set the "grid2 pixel" skin to 1 pixel but that didnt work. re-upping that to 8 pixels made it visible again.
