### ISSUE TITLE
Blizzard hotfix in 11/16/23 removed CheckInteractDistance()

### ISSUE THREAD

**Issue by BigFire321** [Dicebar/Raven#56]
26x [ADDON_ACTION_BLOCKED] AddOn 'Raven' tried to call the protected function 'CheckInteractDistance()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `CheckInteractDistance'
[string "@Raven/Conditions.lua"]:226: in function <Raven/Conditions.lua:224>
[string "@Raven/Conditions.lua"]:833: in function `UpdateConditions'
[string "@Raven/Main.lua"]:1278: in function `Update'
[string "@Raven/Main.lua"]:936: in function <Raven/Main.lua:932>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

**Comment by Zaranusta** [comment]
I have the same Problem

**Comment by Dicebar** [comment]
That's a sad one.

Looks like Blizzard is blocking addons from reading range information to prevent boss mods from telling players to spread/stack, and the functionality in Raven is a casualty of that.

Anyway, thanks for the report. I removed range check support from conditions.
