### ISSUE TITLE
Sparkler animation doesn't work properly

### ISSUE THREAD

**Issue by idevels** [Dicebar/raven#6]
1x Interface/AddOns/Raven/Nest.lua:462: bad argument #&#x2060;1 to 'SetTarget' (Usage: local success = self:SetTarget(target))
[string "=[C]"]: in function `SetTarget'
[string "@Interface/AddOns/Raven/Nest.lua"]:462: in function <Interface/AddOns/Raven/Nest.lua:429>
[string "@Interface/AddOns/Raven/Nest.lua"]:2044: in function <Interface/AddOns/Raven/Nest.lua:2014>
[string "@Interface/AddOns/Raven/Nest.lua"]:2703: in function `Nest_Update'
[string "@Interface/AddOns/Raven/Main.lua"]:1220: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:895: in function <Interface/AddOns/Raven/Main.lua:891>

Locals:
(*temporary) = Alpha {
 0 = <userdata>
}
(*temporary) = "Raven_Animation1_Spark1"

**Comment by Dicebar** [comment]
Hey! This issue has been fixed in the latest release.

Thanks for the report 👍
