### ISSUE TITLE
Addon doesn't show buffs/debuffs

### ISSUE THREAD

**Issue by Nethermoure** [Dicebar/Raven#63]
After the last update addon doesn't work for me, got that errors -

15x Raven/Main.lua:1690: attempt to call global 'GetNumTrackingTypes' (a nil value)
[string "@Raven/Main.lua"]:1690: in function <Raven/Main.lua:1685>
[string "@Raven/Main.lua"]:1864: in function `UnitStatusUpdate'
[string "@Raven/Main.lua"]:1452: in function `UnitHasDebuff'
[string "@Raven/Conditions.lua"]:531: in function <Raven/Conditions.lua:421>
[string "@Raven/Conditions.lua"]:687: in function <Raven/Conditions.lua:679>
[string "@Raven/Conditions.lua"]:820: in function `UpdateConditions'
[string "@Raven/Main.lua"]:1283: in function `Update'
[string "@Raven/Main.lua"]:941: in function <Raven/Main.lua:937>
[string "@Raven/Main.lua"]:972: in function `?'
[string "@!KalielsTracker/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@!KalielsTracker/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@!KalielsTracker/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
found = false
trackingTypes = nil
(*temporary) = nil
(*temporary) = "attempt to call global 'GetNumTrackingTypes' (a nil value)"
MOD = <table> {
 CheckTalent = <function> defined @Raven/Conditions.lua:321
 testOrder = <table> {
 }
 HexColor = <function> defined @Raven/Profile.lua:43
 UpdateInCombatBar = <function> defined @Raven/Cancel.lua:66
 modules = <table> {
 }
 Nest_SetShine = <function> defined @Raven/Nest.lua:1303
 GetValueFormat = <function> defined @Raven/Values.lua:832
 ReleaseBarGroup = <function> defined @Raven/Bars.lua:723
 CopyTable = <function> defined @Raven/Profile.lua:61
 ResetColorDefault = <function> defined @Raven/Profile.lua:477
 Nest_SetBarGroupLock = <function> defined @Raven/Nest.lua:973
 Nest_FormatTime = <function> defined @Raven/Nest.lua:1873
 SetInCombatBar = <function> defined @Raven/Cancel.lua:203
 LocalSpellNames = <table> {
 }
 GetExpireColor = <function> defined @Raven/Profile.lua:694
 UpdateInternalCooldowns = <function> defined @Raven/Main.lua:2133
 SetExpireColor = <function> defined @Raven/Profile.lua:682
 DefaultProfile = <table> {
 }
 ResetColorDefaults = <function> defined @Raven/Profile.lua:496
 RemoveMatchingTrackers = <function> defined @Raven/Main.lua:418
 Nest_CreateBar = <function> defined @Raven/Nest.lua:1074
 CheckSpec = <function> defined @Raven/Conditions.lua:376
 SetEnabledState = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:420
 FinalizeBars = <function> defined @Raven/Bars.lua:161
 mountSpells = <table> {
 }
 Nest_SetLabelColor = <function> defined @Raven/Nest.lua:1279
 LoadCustomBars = <function> defined @Raven/Bars.lua:528
 Nest_DeleteAllBars = <function> defined @Raven/Nest.lua:1243
 Nest_AdjustColor = <function> defined @Raven/Nest.lua:1344
 UpdateTrackers = <function> defined @Raven/Main.lua:1884
 ldbi = <table> {
 }
 Nest_RegisterCallbacks = <function> defined @Raven/Nest.lua:683
 UnregisterAllEvents = <function> defined @!KalielsTracker/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 InitializeBarGroup = <function> defined @Raven/Bars.lua:494
 Nest_SetBarGroupBorder = <function> defined @Raven/Nest.lua:898
 Nest_GetBarGroups = <function> defined @Raven/Nest.lua:796
 HideBars = <function> defined @Raven/Bars.lua:175
 OptionsPanel = <function> defined @Raven/Main.lua:1124
 Nest_SetBarGroupBackdrop = <function> defined @Raven/Nest.lua:906
 DetectInternalCooldown = <function> defined @Raven/Main.lua:2115
 Nest_SetColors = <function> defined @Raven/Nest.lua:1262
 isVanilla = false
 InitializeSpellIDs = <function> defined @Raven/Profile.lua:141
 GetName = <function> defined @!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:275
 InitializeBuffTooltip = <function> defined @Raven/Main.lua:1464
 name = "Raven"
 ColorPalette = <table> {
 }
 SetConditionDefaults = <function> defined @Raven/Conditions.lua:848
 Nest_SetAlpha = <function> defined @Raven/Nest.lua:1294
 SaveBarGroupSettings = <function> defined @Raven/Bars.lua:525
 Print = <function> defined @Bartender4/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 RegisterCooldownDefault = <function> defined @Raven/Profile.lua:407
 Nest_SetTimeColor = <function> defined @Raven/Nest.lua:1284
 Nest_DeleteBar = <function> defined @Raven/Nest.lua:1179
 ExpansionIsOrBelow = <function> defined @Raven/Main.lua:46
 UpdateSpellEffects =

**Comment by Dicebar** [comment]
I've been fixing bugs for classic and wound up breaking something on retail, sorry!

Thanks for the report. This should be fixed in r646.
