### ISSUE TITLE
Split disabling of Blizzard buffs/debuffs

### ISSUE THREAD

**Issue by Tenga** [Dicebar/Raven#64]
Currently, when hiding Blizzard player buffs and debuffs through Raven, they are disabled together as a single toggle. I hoped to use Raven to replace the debuffs, while keeping the Blizzard buffs.

I did some hands-on and commented out the stuff in `ShowHide` that affects the `BuffFrame`, and the tweak appears to work for my purposes. (My first time meddling with WoW addon code, so I might be unaware of my sins. 😁)

I believe that splitting the buff/debuff hide toggle would be technically possible since Dragonflight? Apologies if this has been brought up before, I searched, but didn't get anything similar.

**Comment by Dicebar** [comment]
It's definitely possible. I prepared an update to add this, and it all seems to work.

However, I won't be home much over the weekend, so I'll hold off on releasing the feature until Tuesday when I'll have time to respond to any bugs the update might introduce.

**Comment by Dicebar** [comment]
Sorry for delaying the release for this by a week, I had some real life distractions T-bone me. It will be coming _this_ Tuesday!

**Comment by Dicebar** [comment]
Did I say Tuesday? I obviously meant _Thursday_. Uh huh.

It's out!
