### ISSUE TITLE
Enemy buffs not showing

### ISSUE THREAD

**Issue by Eegjrgngdbnreegbue** [Dicebar/Raven#65]
Raven is no longer showing buffs on enemies, on classic era and season of discovery servers. For example making an auto group to show all buffs on the target, will show the buffs when targeting a friendly player but not an enemy player or hostile npc. Debuffs works fine.

If it is any help, ClassicAuraDurations had the same issue and solved it with an update in the library LibClassicDurations. I see that Raven is using the same library, however simply updating this library in the Raven folder does not solve the issue.

**Comment by Dicebar** [comment]
Thanks for the report!

I've started leveling a classic era character to test this properly.

**Comment by Dicebar** [comment]
Found it!

This should be fixed in r650.
