### ISSUE TITLE
Horn of Winter - Wrath Classic

### ISSUE THREAD

**Issue by volostyle** [Dicebar/Raven#66]
Hi, I'm using the "Long Buff" and "Short Buff" groups. I'm noticing that Horn of Winter is always showing up in the "Long" group, even though the duration is less than 2 mins. Is that intended? I was under the impression that anything under 2 mins should be in the short buff group.

**Comment by Dicebar** [comment]
[Horn of Winter](https://www.wowhead.com/wotlk/spell=57330/horn-of-winter) lasts exactly 2 minutes, so it sits right on the boundary between long and short buffs. However, buffs are considered long when they are _at least_ 2 minutes, so Horn of Winter falls into that category (barely).
