### ISSUE TITLE
Please update for Cata classic prepatch. 

### ISSUE THREAD

**Issue by theoriginalmre** [Dicebar/Raven#71]
Current lua error on login:

1x Raven/Main.lua:1031: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@Raven/Main.lua"]:1031: in function `BAG_UPDATE'
[string "@Raven/Main.lua"]:856: in function <Raven/Main.lua:846>
[string "=[C]"]: ?
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Bartender4/libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:626: in function <Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals:
self = <table> {
 CheckTalent = <function> defined @Raven/Conditions.lua:398
 testOrder = <table> {
 }
 HexColor = <function> defined @Raven/Profile.lua:43
 UpdateInCombatBar = <function> defined @Raven/Cancel.lua:66
 modules = <table> {
 }
 Nest_SetShine = <function> defined @Raven/Nest.lua:1303
 GetValueFormat = <function> defined @Raven/Values.lua:833
 ReleaseBarGroup = <function> defined @Raven/Bars.lua:723
 CopyTable = <function> defined @Raven/Profile.lua:61
 ResetColorDefault = <function> defined @Raven/Profile.lua:487
 Nest_SetBarGroupLock = <function> defined @Raven/Nest.lua:973
 Nest_FormatTime = <function> defined @Raven/Nest.lua:1873
 SetInCombatBar = <function> defined @Raven/Cancel.lua:203
 LocalSpellNames = <table> {
 }
 GetExpireColor = <function> defined @Raven/Profile.lua:704
 UpdateInternalCooldowns = <function> defined @Raven/Main.lua:2125
 SetExpireColor = <function> defined @Raven/Profile.lua:692
 DefaultProfile = <table> {
 }
 ResetColorDefaults = <function> defined @Raven/Profile.lua:506
 RemoveMatchingTrackers = <function> defined @Raven/Main.lua:407
 Nest_CreateBar = <function> defined @Raven/Nest.lua:1074
 CheckSpec = <function> defined @Raven/Conditions.lua:453
 SetEnabledState = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:420
 FinalizeBars = <function> defined @Raven/Bars.lua:161
 mountSpells = <table> {
 }
 Nest_SetLabelColor = <function> defined @Raven/Nest.lua:1279
 LoadCustomBars = <function> defined @Raven/Bars.lua:528
 Nest_DeleteAllBars = <function> defined @Raven/Nest.lua:1243
 Nest_AdjustColor = <function> defined @Raven/Nest.lua:1344
 UpdateTrackers = <function> defined @Raven/Main.lua:1876
 ldbi = <table> {
 }
 Nest_RegisterCallbacks = <function> defined @Raven/Nest.lua:683
 UnregisterAllEvents = <function> defined @LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 InitializeBarGroup = <function> defined @Raven/Bars.lua:494
 Nest_SetBarGroupBorder = <function> defined @Raven/Nest.lua:898
 Nest_GetBarGroups = <function> defined @Raven/Nest.lua:796
 HideBars = <function> defined @Raven/Bars.lua:175
 OptionsPanel = <function> defined @Raven/Main.lua:1111
 Nest_SetBarGroupBackdrop = <function> defined @Raven/Nest.lua:906
 DetectInternalCooldown = <function> defined @Raven/Main.lua:2107
 Nest_SetColors = <function> defined @Raven/Nest.lua:1262
 warlockCreatures = <table> {
 }
 InitializeSpellIDs = <function> defined @Raven/Profile.lua:141
 GetName = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:275
 InitializeBuffTooltip = <function> defined @Raven/Main.lua:1451
 name = "Raven"
 Disable = <function> defined @Bartender4/libs/AceAddon-3.0/AceAddon-3.0.lua:310
 SetConditionDefaults = <function> defined @Raven/Conditions.lua:937
 Nest_SetAlpha = <function> defined @Raven/Nest.lua:1294
 SaveBarGroupSettings = <function> defined @Raven/Bars.lua:525
 Print = <function> defined @Bartender4/libs/AceConsole-3.0/AceConsole-3.0.lua:50
 RegisterCooldownDefault = <function> defined @Raven/Profile.lua:417
 Nest_SetTimeColor = <function> defined @Raven/Nest.lua:1284
 Nest_DeleteBar = <function> defined @Raven/Nest.lua:1179
 ExpansionIsOrBelow = <function> defined @Raven/Main.lua:49
 UpdateSpellEffects = <function> defined @Raven/Main.lua:1724

**Comment by Dicebar** [comment]
There are Cata-specific bugs that I'm working on, but his looks like a bug that's already been fixed in r651.

Are you running the latest version of Raven?

**Comment by theoriginalmre** [comment]
Yes I believe so. Unless the link on Curseforge wasn't the latest.

**Comment by theoriginalmre** [comment]
After updating to the latest version r652, the only error I get left is when I apply poisons to my weapons on a a rogue:

1x Raven/Main.lua:1499: attempt to index global 'C_TooltipInfo' (a nil value)
[string "@Raven/Main.lua"]:1499: in function <Raven/Main.lua:1498>
[string "@Raven/Main.lua"]:1572: in function <Raven/Main.lua:1555>
[string "@Raven/Main.lua"]:1953: in function `UpdateAuras'
[string "@Raven/Main.lua"]:1279: in function `Update'
[string "@Raven/Main.lua"]:951: in function <Raven/Main.lua:947>

**Comment by cl0udc4ller** [comment]
Have still this error after latest update r652

Message: Interface/AddOns/Raven/Main.lua:1499: attempt to index global 'C_TooltipInfo' (a nil value)
Time: Thu May  2 10:14:19 2024
Count: 1
Stack: Interface/AddOns/Raven/Main.lua:1499: attempt to index global 'C_TooltipInfo' (a nil value)
[string "@Interface/AddOns/Raven/Main.lua"]:1499: in function <Interface/AddOns/Raven/Main.lua:1498>
[string "@Interface/AddOns/Raven/Main.lua"]:1572: in function <Interface/AddOns/Raven/Main.lua:1555>
[string "@Interface/AddOns/Raven/Main.lua"]:1953: in function `UpdateAuras'
[string "@Interface/AddOns/Raven/Main.lua"]:1279: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:951: in function <Interface/AddOns/Raven/Main.lua:947>
[string "@Interface/AddOns/Raven/Main.lua"]:982: in function `?'
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:119: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:29: in function <...her/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@Interface/AddOns/BagBrother/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface/AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BagBrother/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: weaponSlot = 16
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_TooltipInfo' (a nil value)"

**Comment by Dicebar** [comment]
Thanks for the reports!

The C_TooltipInfo bug should  be fixed as of r563.
