### ISSUE TITLE
Cata Classic - Thrown Weapon poison tracking

### ISSUE THREAD

**Issue by theoriginalmre** [Dicebar/Raven#72]
Are you able to implement a tracking for the poison that rogues can apply to Thrown Weapons in their ranged slot now?

**Comment by Dicebar** [comment]
It should be available in r655, if I did it right.

Could you test that once it's deployed to CurseForge?

**Comment by theoriginalmre** [comment]
Of course.
Can't play without my Raven :)

**Comment by theoriginalmre** [comment]
Problem with r655 is that it's now not tracking Poison on the Offhand weapon.
Also, the Thrown weapon poison buff has no weapon tooltip. But this is minor.

**Comment by Dicebar** [comment]
I misnamed something, which may have been overriding the offhand data. r656 might do the trick!

**Comment by theoriginalmre** [comment]
r656 bugged. Also the same issues from r655 (can't see offhand poison):

1x AceLocale-3.0-6: Raven: Missing entry for 'Ranged Weapon'
[string "@Raven/Main.lua"]:1643: in function <Raven/Main.lua:1557>
[string "@Raven/Main.lua"]:1986: in function `UpdateAuras'
[string "@Raven/Main.lua"]:1281: in function `Update'
[string "@Raven/Main.lua"]:953: in function <Raven/Main.lua:949>
[string "@Raven/Main.lua"]:984: in function `?'
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...edia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@LibSharedMedia-3.0-8020003/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@AutoCombatLogger/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <.../AutoCombatLogger/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
hasMainHandEnchant = true
mainHandExpiration = 0
mainHandCharges = 0
_ = 323
hasOffHandEnchant = true
offHandExpiration = 0
offHandCharges = 0
_ = 7
hasRangedEnchant = true
rangedExpiration = 0
rangedCharges = 0
_ = 703
invSlot = 18
rangedBuff = nil
weaponLink = "|cffffffff|Hitem:50474::::::::80:::::::::|h[]|h|r"
(*temporary) = <table> {
 On Target = "On Target"
 Adjust Segments = "Adjust Segments"
 If checked, only show bar-specific special effects, otherwise also show bar group special effects. = "If checked, only show bar-specific special effects, otherwise also show bar group special effects."
 Bar group anchor string = "Bar groups have anchors that show where bars will be displayed. Anchor tooltips list helpful shortcuts (e.g., change direction bars grow from the anchor, cycle through configuration choices, show test bars). You can left-click and drag anchors. You can right-click an anchor to lock it when you are satisfied with its position. Locked anchors are hidden--use the "Unlock All Anchors" button to show them again.
"
 If checked, test the target's target maximum health. = "If checked, test the target's target maximum health."
 Is Enemy = "Is Enemy"
 If checked, test if the target's target is an enemy. = "If checked, test if the target's target is an enemy."
 Bar Configuration = "Bar Configuration"
 Reset bar colors back to default. = "Reset bar colors back to default."
 Locked out of Arcane school of magic. = "Locked out of Arcane school of magic."
 Include all debuffs cast by player on others. = "Include all debuffs cast by player on others."
 If checked, circles are shown instead of rectangular segments. = "If checked, circles are shown instead of rectangular segments."
 If checked, Raven will not play sound effects. = "If checked, Raven will not play sound effects."
 All Debuffs = "All Debuffs"
 If checked, select shaman actions. = "If checked, select shaman actions."
 Hide Azerite bar in the default user interface. = "Hide Azerite bar in the default user interface."
 If checked, focus's health must be at least this percentage, otherwise must be less. = "If checked, focus's health must be at least this percentage, otherwise must be less."
 Dispel = "Dispel"
 Raven shift right click = "|cffffff00Shift-right-click|r to toggle Blizzard buffs"
 Normal Opacity = "Normal Opacity"
 Reset color and label confirm = <function> defined @Raven/Localizations/enUS.lua:548
 Label Text Inset = "Label Text Inset"
 If checked, filter list includes spells in specified spell list (these are set up on the Spells tab). = "If checked, filter list includes spells in specified spell list (these are set up on the Spells tab)."
 Font = "Font"
 Show alerts for buff spells cast on enemies. = "Show alerts for buff spells cast on enemies."
 Auto Adjust = "Auto Adjust"
 If checked, stripe is above the anchor, otherwise it is below the anchor. = "If checked, stripe is above the anchor, otherwise it is below the anchor."
 Enter a label to be used by default with this spell. = "Enter a label to be used by default with this spell."
 Source = "Source"
 Frame Stack = "Frame Stack"
 Unit Frame = "Unit Frame"
 Last Bar = "Last Bar"
 Enter the creature family to check for (enter "none" to check if not applicable). = "Enter the creature family to check for (enter "none" to check if not applicable)."
 Spell ID (Tooltip) = "Spell ID (Tooltip)"
 Set fade opacity for buff icon when mouseover is not detected. = "Set fade opacity for buff icon when mouseover is not detected."
 If checked, player must have at least this amount of insanity, otherwise must be less. = "If checked, player must have at least this amount of insanity, otherwise must be less."
 Cast Bar = "Cast Bar"
 If checked, test the target's target power (i.e., mana, rage, energy, focus, runic power). = "If checked, test the target's target power (i.e., mana, rage, energy, focus, runic power)."
 Stance String = <function> defined @Raven/Localizations/enUS.lua:119
 If checked, combat text includes the name of the bar group. = "If checked, combat text inclu

**Comment by Dicebar** [comment]
The fact that that error is showing up now is promising... I've tweaked things further in r657 🙏

**Comment by theoriginalmre** [comment]
r657 - no lua errors, but no Offhand Poison buff still :(
Also no Thrown Weapon tooltip. Just says "Applied by character"

**Comment by Dicebar** [comment]
> r657 - no lua errors, but no Offhand Poison buff still :(

r658 should though 😎 I released that a minute later, but you were too quick!

>  Also no Thrown Weapon tooltip. Just says "Applied by character"

That one is more complicated... I'll have to think about this one.

**Comment by theoriginalmre** [comment]
r658 is a success!
However, there's still no tooltip on the Thrown Weapon buff for the poison. But I can live with that lol.

**Comment by Dicebar** [comment]
I can't! 😂

I think I found it, though. r659 coming up!

**Comment by theoriginalmre** [comment]
r659 still the same as previous version. No change.

**Comment by Dicebar** [comment]
One more fix, one more version. r660 incoming!

**Comment by theoriginalmre** [comment]
r660 success!
Tooltip shows properly and no lua errors.

**Comment by Dicebar** [comment]
Awesome, thanks for the help! 🥳
