### ISSUE TITLE
Lag while crafting cloth

### ISSUE THREAD

**Issue by beeeeee2** [Dicebar/Raven#74]
Very slight stutter experienced when crafting bolts of frostweave, imbued frostweave, spellweave, ebonweave and moonshroud cloth.  cata pre release, r5 5600, rx 6600, 16gb 3200, im at 120fps in org but crafting drops me to 50-60 with raven enabled

**Comment by Dicebar** [comment]
Is it specifically those materials or any kind of crafting?

**Comment by beeeeee2** [comment]
after playing a bit this afternoon, its pretty much at the end of a cast with particle effects, other players casts dont seem to affect me, just on completion of my own casts.

**Comment by beeeeee2** [comment]
update! i believe it was client side, the weekly maintenance seemed to have fixed everything!

**Comment by Dicebar** [comment]
That's great to hear, thanks for the update!
