### ISSUE TITLE
No bar groups want to show up

### ISSUE THREAD

**Issue by Japie1245** [Dicebar/Raven#82]
I made some long buffs and short buffs auto bar groups i tried unlocking them using test mode but they wont show up, I also got this thing in bugsack, i also got this error but instead of "range" in the first line "in range" "out of range" and "target in range":
1x AceLocale-3.0-6: Raven: Missing entry for 'Range'
[string "@Raven_Options/Options.lua"]:11164: in main chunk
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Raven/Main.lua"]:1129: in function `OptionsPanel'
[string "@Raven/Main.lua"]:875: in function `?'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5440: in function <Blizzard_ChatFrameBase/Mainline/ChatFrame.lua:5386>
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5092: in function `ChatEdit_SendText'
[string "@Blizzard_ChatFrameBase/Mainline/ChatFrame.lua"]:5128: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:140_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:140_OnEnterPressed"]:1>

Locals:
MOD = <table> {
 testOrder = <table> {
 }
 modules = <table> {
 }
 LocalSpellNames = <table> {
 }
 DefaultProfile = <table> {
 }
 mountSpells = <table> {
 }
 ldbi = <table> {
 }
 isVanilla = false
 professionSpells = <table> {
 }
 ColorPalette = <table> {
 }
 ClassColors = <table> {
 }
 combatTimer = 0
 runeSlots = <table> {
 }
 lockoutSpells = <table> {
 }
 isModernUI = true
 status = <table> {
 }
 LibBossIDs = <table> {
 }
 BarGroupTemplate = <table> {
 }
 petSpells = <table> {
 }
 talents = <table> {
 }
 BarGroupLayoutTemplate = <table> {
 }
 lockSpells = <table> {
 }
 TopOptionsTable = <table> {
 }
 runeCount = 0
 Nest_MaxBarConfiguration = 8
 localRace = "Pandaren"
 updateActions = true
 isWrath = false
 db = <table> {
 }
 bookSpells = <table> {
 }
 LibLDB = <table> {
 }
 ldb = <table> {
 }
 myRace = "Pandaren"
 suppress = false
 localClass = "Shaman"
 myClass = "SHAMAN"
 baseName = "Raven"
 warlockCreatures = <table> {
 }
 runeSpells = <table> {
 }
 isCata = false
 Nest_TimeFormatOptions = <table> {
 }
 brokerList = <table> {
 }
 updateOptions = false
 updateDispels = true
 knownBrokers = <table> {
 }
 enabledState = true
 chargeSpells = <table> {
 }
 frame = Frame {
 }
 isClassic = false
 conditionTests = <table> {
 }
 Nest_SupportedConfigurations = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "Raven"
 SHIM = <table> {
 }
 orderedModules = <table> {
 }
 talentList = <table> {
 }
 cooldownSpells = <table> {
 }
 defaultModuleState = true
}
acereg = <table> {
 validated = <table> {
 }
 tables = <table> {
 }
 callbacks = <table> {
 }
}
acedia = <table> {
 tooltip = AceConfigDialogTooltip {
 }
 BlizOptions = <table> {
 }
 popup = Frame {
 }
 OpenFrames = <table> {
 }
 Status = <table> {
 }
 frame = Frame {
 }
}
L = <table> {
 On Target = "On Target"
 Adjust Segments = "Adjust Segments"
 If checked, only show bar-specific special effects, otherwise also show bar group special effects. = "If checked, only show bar-specific special effects, otherwise also show bar group special effects."
 Bar group anchor string = "Bar groups have anchors that show where bars will be displayed. Anchor tooltips list helpful shortcuts (e.g., change direction bars grow from the anchor, cycle through configuration choices, show test bars). You can left-click and drag anchors. You can right-click an anchor to lock it when you are satisfied with its position. Locked anchors are hidden--use the "Unlock All Anchors" button to show them again.
"
 If checked, test the target's target maximum health. = "If checked, test the target's target maximum health."
 Is Enemy = "Is Enemy"
 If checked, test if the target's target is an enemy. = "If checked, test if the target's target is an enemy."
 Bar Configuration = "Bar Configuration"
 Reset bar colors back to default. = "Reset bar colors back to default."
 Locked out of Arcane school of magic. = "Locked out of Arcane school of magic."
 Include all debuffs cast by player on others. = "Include all debuffs cast by player on others."
 If checked, circles are shown instead of rectangular segments. = "If checked, circles are shown instead of rectangular segments."
 If checked, Raven will not play sound effects. = "If checked, Raven will not play sound effects."
 All Debuffs = "All Debuffs"
 If checked, select shaman actions. = "If checked, select shaman actions."
 Hide Azerite bar in the default user interface. = "Hide Azerite bar in the default user interface."
 If checked, focus's health must be at least this percentage, otherwise must be less. = "If checked, focus's health must be at least this percentage, otherwise must be less."
 Dispel = "Dispel"
 Raven shift right click = "|cffffff00Shift-right-click|r to toggle Blizzard buffs"
 Normal Opacity = "Normal Opacity"
 Label Text Inset = "Label Text Inset"
 If checked, filter list includes spells in specified spell list (these are set up on the Spells tab). = "If checked, filter list includes spells in specified spell list (these are set up on the Spells tab)."
 Font = "Font"
 Show alerts for buff spells cast on enemies. = "Show alerts for buff

**Comment by Dicebar** [comment]
It looks like you're using an outdated version of Raven_Options. To complicate matters, it's currently not included in our release on CurseForge due to a bug.

Can you try this version?

https://www.dicebar.net/files/Raven_Options.zip

**Comment by Japie1245** [comment]
that was it tysm, my options were not there so i took them from another random folder on my pc turns out they were outdated

**Comment by Japie1245** [comment]
it worked but i couldnt lock my anchors, i reloaded and now i have the same issue as before. No error this time

**Comment by vojtasrb** [comment]
Same problem. Updated to newest version but no icons, no bars show up.

**Comment by Dicebar** [comment]
CurseForge's packager was excluding Raven_Options for some reason. I've updated our release workflow and as of `r668` Raven_Options should be back in the release.

Can you update to that release and let me know if the problem persists?

**Comment by Japie1245** [comment]
i can only check a little bit cuz i have to go but i think everything is working as it should be

**Comment by Dicebar** [comment]
> i can only check a little bit cuz i have to go but i think everything is working as it should be

Fair enough! If you run into more problems don't hesitate to let me know.

**Comment by vojtasrb** [comment]
Still not showing up for me. I don't know where could be the problem as there are no LUA errors from Raven. I tried disabling/enabling them, unlocking/locking the anchors, manually reposition them. They just don't exist.

**Comment by Japie1245** [comment]
everything is working fine for me now

**Comment by Japie1245** [comment]
> Still not showing up for me. I don't know where could be the problem as there are no LUA errors from Raven. I tried disabling/enabling them, unlocking/locking the anchors, manually reposition them. They just don't exist.

make sure its in the right folder cuz i had 2 addon folders on my pc for some reason

**Comment by vojtasrb** [comment]
> make sure its in the right folder cuz i had 2 addon folders on my pc for some reason

It is. I tried to reinstall it, still not working. Downloaded Aura Frames, 7 years old version lol... and that works fine.

**Comment by CamalusWoW** [comment]
I'm having the same problem but it's character specific. They show on my Priest but won't show on my Dracthyr.

```
1x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Raven/Main.lua"]:1094: in function <Raven/Main.lua:1065>
[string "@Raven/Main.lua"]:1274: in function `Update'
[string "@Raven/Main.lua"]:953: in function <Raven/Main.lua:949>
[string "@Raven/Main.lua"]:984: in function `?'
[string "@BlizzMove/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ove/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@BlizzMove/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ove/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@BlizzMove/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BlizzMove/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <BlizzMove/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"
```

**Comment by Japie1245** [comment]
i just logged on to my other char where i get the error of raven options missing again (i was playing on an alt so i just realized this)

**Comment by Dicebar** [comment]
> i just logged on to my other char where i get the error of raven options missing again (i was playing on an alt so i just realized this)

For whatever reason CurseForge repackaged an earlier release, removing Raven_Options. Might be lag in updating the settings for everything. 

Note the filesize difference on CF:
![image](https://github.com/user-attachments/assets/d652d972-f760-47d2-88cd-3e4b81b9f108)

**Comment by Dicebar** [comment]
@CamalusWoW:
> I'm having the same problem but it's character specific.

I think I narrowed down that problem. Can you try `r670`?

**Comment by Japie1245** [comment]
its working on both chars for me now

**Comment by CamalusWoW** [comment]
@Dicebar thanks for looking into it! Unfortunately still encountering the problem in `r670`

**Comment by vojtasrb** [comment]
Yeah, still not working for me

**Comment by vojtasrb** [comment]
Yeah, still not working for me

Message: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
Time: Wed Jul 24 23:39:53 2024
Count: 1
Stack: bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "@Interface/AddOns/Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Interface/AddOns/Raven/Main.lua"]:1094: in function <Interface/AddOns/Raven/Main.lua:1065>
[string "@Interface/AddOns/Raven/Main.lua"]:1274: in function `Update'
[string "@Interface/AddOns/Raven/Main.lua"]:953: in function <Interface/AddOns/Raven/Main.lua:949>
[string "@Interface/AddOns/Raven/Main.lua"]:984: in function `?'
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...que/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/Masque/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: self = <table> {
}
spellID = nil

**Comment by Zasz333** [comment]
I have the same issue with the latest version. Bars wont show up without an error.

Im using one profile for all toons. It works on my bank toon but not on my demon hunter. Earlier it worked on my monk until I noticed the timers didnt count down. I reloaded with /reload and the bars just disappeared.

Then I downloaded it directly from curse just a few minutes ago and it works on my monk. But still not on my demon hunter. Now Im getting this:

51x bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))
[string "=[C]"]: in function `GetSpellInfo'
[string "@Raven/Shims.lua"]:88: in function `GetSpellInfo'
[string "@Raven/Profile.lua"]:358: in function `SetCooldownDefaults'
[string "@Raven/Main.lua"]:1026: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local spellInfo = C_Spell.GetSpellInfo(spellIdentifier))"


Now the buff bar is there but no new buffs appear nor does the only active buff count down. Debuffs dont appear either.

**Comment by Dicebar** [comment]
Hi @Zasz333: I pushed a fix for the Demon Hunter problem literally a minute or two ago. It should be fixed with `r673`. Can you confirm?

**Comment by Zasz333** [comment]
My typical timing...

Confirmed fixed. Works on my demon hunter. Also fixed the same issue on my evoker. Also fixed on my monk.

Huge thanks. Great work :)

**Comment by vojtasrb** [comment]
> Hi @Zasz333: I pushed a fix for the Demon Hunter problem literally a minute or two ago. It should be fixed with `r673`. Can you confirm?

After downloading r673, it finally started working. Thanks a lot.

**Comment by Dicebar** [comment]
You're welcome! :)

**Comment by Dicebar** [comment]
@CamalusWoW:

Has your issue been resolved as well?

**Comment by CamalusWoW** [comment]
@Dicebar yes, works for me now. Thanks!

**Comment by Dicebar** [comment]
Sweet, glad to hear it!
