### ISSUE TITLE
Raven works on almost every character

### ISSUE THREAD

**Issue by Koskun** [Dicebar/Raven#88]
I have every class at 70.   Through all the update shenanigans that are an expansion pre-patch, this one came through with all settings just fine, except...

My Monk, Demon Hunter, and Evoker, as well as a few other low level "I have them because uhh" have no display of anything from Raven at all.  Raven loads fine.  I can open the options page fine.  I can click things in said options pages.  However nothing is shown.  Even if I un-check "Hide Blizzard" those don't show up either, though that happens on all characters.

For whatever reason, absolutely nothing shows up anywhere on my screen on those characters.  It almost feels like it is working, but it is somewhere off screen.  I've had that issue with one or two WeakAura's in the past.

If I reset the profile, nothing.  If I have only Raven loaded and no other addons, nothing.  I even deleted the Raven and Raven bak lua's out (saved a copy of course), and still nothing from Raven shows up on those characters.  The only thing that shows up from Raven is the grid from "Toggle Overlay".  If I try to create anything new, Buffs, Timeline, Debuffs, nothing shows anywhere on the screen.

**Comment by Dicebar** [comment]
Hi @Koskun!

A bugfix just went out where I solved a problem for Demon Hunters specifically, but logging into my monk and evoker confirms that they were affected as well.

This should hopefully be fixed as of `r673`. Can you confirm?

**Comment by Koskun** [comment]
Hopped on the DH, Monk, and Evoker.  It's back and working as it should on them.

Much appreciate the speedy reply and update.

**Comment by Dicebar** [comment]
Glad to hear it, thanks!
