### ISSUE TITLE
Raven is not working on some classes.

### ISSUE THREAD

**Issue by ShinTeach** [Dicebar/Raven#89]
Seems like something broke with today's update. The addon is not working with some of my characters and it appears to be class-related. 
It works fine on my warriors and my demon hunter, but it's not working on my paladins, my druid or my death knight. I have not tested it on other classes. 
The addon recognises the bar groups exist, but they are not displayed anywhere on screen, even after a reset. I've disabled all my addons on these characters and the problem persists.

**Comment by Mortarinya** [comment]
I tested this on each class (and multiples of a given class in some cases). I used the same profile on all characters. I also tried creating a completely new profile and resetting it to defaults, but this does not fix the issue. All of the characters show that the bar groups exist in the options, but for some classes they are not displayed. Disabling all other addons also doesn't fix the issue.

Currently, the groups display fine on: Warrior, Evoker, Demon Hunter

Not working for: Paladin, Death Knight, Hunter, Shaman, Rogue, Druid, Monk, Warlock, Priest, Mage

**Comment by Tovrin** [comment]
1x Raven/Shims.lua:253: attempt to call global 'GetSpellCooldown' (a nil value)
[string "@Raven/Shims.lua"]:253: in function `GetSpellBookItemCooldown'
[string "@Raven/Main.lua"]:2229: in function `UpdateCooldowns'
[string "@Raven/Main.lua"]:1291: in function `Update'
[string "@Raven/Main.lua"]:954: in function <Raven/Main.lua:950>
[string "@Raven/Main.lua"]:985: in function `?'
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...lic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Altoholic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bears_Audio_Switcher/Libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...rs_Audio_Switcher/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
}
index = 72
spellBank = "spell"
(*temporary) = nil
(*temporary) = 72

**Comment by Dicebar** [comment]
I'll be having a look in a few hours, thanks for the reports!

**Comment by Dicebar** [comment]
This should be fixed as of `r679`. If people could confirm their problem is fixed, that'd be great. Thanks!

**Comment by Tovrin** [comment]
Jumped on quickly with my druid and it seems to be working again.  Thanks!

**Comment by ShinTeach** [comment]
Tested all my toons and it's working again. Thank you!
