### ISSUE TITLE
Addon not working -  LUA error with latest patch

### ISSUE THREAD

**Issue by Andf** [Dicebar/Raven#90]
Hello! 

Unfortunately Raven is not working anymore in 11.0.2, receiving LUA error below.
So far I have seen this error with a Shadow Priest , a Shammy Enha, MM hunter and a Destro Lock.
I'm not receiving this problem with a Fury Warrior.

+++++++++++
3x Raven/Shims.lua:253: attempt to call global 'GetSpellCooldown' (a nil value)
[string "@Raven/Shims.lua"]:253: in function `GetSpellBookItemCooldown'
[string "@Raven/Main.lua"]:2229: in function `UpdateCooldowns'
[string "@Raven/Main.lua"]:1291: in function `Update'
[string "@Raven/Main.lua"]:954: in function <Raven/Main.lua:950>
[string "@Raven/Main.lua"]:985: in function `?'
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ons/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@AdvancedInterfaceOptions/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Bartender4/libs/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Bartender4/libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
}
index = 80
spellBank = "spell"
(*temporary) = nil
(*temporary) = 80
(*temporary) = "spell"
(*temporary) = "attempt to call global 'GetSpellCooldown' (a nil value)"
+++++++++++

**Comment by Dicebar** [comment]
This should be fixed as of `r679`. Thanks for the report!

**Comment by Andf** [comment]
Many thanks for the quick fix, everything looks fine!
