### ISSUE TITLE
Unable to Create New Custome Bars

### ISSUE THREAD

**Issue by coachseat** [Dicebar/Raven#91]
Unable to enter spell names or spell IDs when creating a new bar under 'custom bars' in a custom group. Can type in the name and press enter, but nothing is pulled from either names or IDs

**Comment by zipzip98** [comment]
i think i have same problem. when i want to add "Any Buffs" item to any existing condition and enter buff name, getting those LUA errors,

Message: Interface/AddOns/Raven_Options/Options.lua:86: attempt to call global 'GetSpellTexture' (a nil value)
Time: Thu Aug 15 17:10:05 2024
Count: 3
Stack: Interface/AddOns/Raven_Options/Options.lua:86: attempt to call global 'GetSpellTexture' (a nil value)
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua"]:70: in function <...ons/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:67>
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua"]:118: in function <...ons/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:115>

Message: Interface/AddOns/Raven_Options/Options.lua:86: attempt to call global 'GetSpellTexture' (a nil value)
Time: Thu Aug 15 16:51:41 2024
Count: 1
Stack: Interface/AddOns/Raven_Options/Options.lua:86: attempt to call global 'GetSpellTexture' (a nil value)
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/AceGUI-3.0/AceGUI-3.0.lua"]:300: in function `Fire'
[string "@Interface/AddOns/AdvancedInterfaceOptions/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua"]:70: in function <...ons/libs/AceGUI-3.0/widgets/AceGUIWidget-EditBox.lua:67>

**Comment by Dicebar** [comment]
This was a weird one. Best I can tell this should've been bugged before this week's patch, but I'm pretty sure I have used this very same functionality before the patch as well without issue.

I suspect there's an underlying problem that I'm not aware of, and I haven't been able to track it down.

That being said, I was able to reproduce the bug and fix it. Can you check if `r680` fixes the problem for you?

Thanks for the reports 😊

**Comment by zipzip98** [comment]
> That being said, I was able to reproduce the bug and fix it. Can you check if `r680` fixes the problem for you?

installed r680 and edited existing condition with success. it seems problem solved.

thank you very much, have a nice day :)
