### ISSUE TITLE
Bar groups always behind action bar 1

### ISSUE THREAD

**Issue by dahennessy** [Dicebar/Raven#94]
I'm trying to place some icon timers above my skills on my action bars but for some reason, this works on all action bars except the first. All groups are always behind bar 1 and in front of all other bars. I can't find a setting to control the layer level. Is there an easy way to fix this?

![image](https://github.com/user-attachments/assets/f9dfb10e-0d2a-4d8b-856a-c72c85d92a28)

**Comment by Dicebar** [comment]
Sorry for the late response, I have been unwell.

As to your question, I'm honestly not sure. Both when I'm running Bartender and without, my randomly created bar group specifically to test this fits right over the action bars without issue. If you're running a different addon for managing your action bars, that might be the issue.

**Comment by dahennessy** [comment]
Hi, no worries, hope you're doing better! 
I don't use any addons for my actionbars, just the blizzard standard bars.
If I drag and move a raven bar, it's on top of basically everything, but as soon as I let go, it jumps behind a few UI elements: 
Actionbar1, Extra Abilities, Encounter bar (Vigor points indicator) and the Shift-M zone minimap.

Oddly enough, the keybinds on the bars shine through raven as well on every actionbar. Here's another screenshot:
![image](https://github.com/user-attachments/assets/d19c6317-dd53-4624-8c6a-dbc89a42dc6c)

![image](https://github.com/user-attachments/assets/418c2122-1de0-416e-bd37-075ab95b3260)

**Comment by Dicebar** [comment]
Thanks for the concern, I am slowly getting better yes 😊

I see it now, yeah. If you set the frame strata for the bar on "high", I think the problem should be resolved:

![image](https://github.com/user-attachments/assets/79183f71-f78c-4b64-ac4b-e920328a3679)

**Comment by dahennessy** [comment]
Amazing, that solved it, thank you so much! Didn't even notice this setting, I just recently found out that it's called strata while searching for a fix that i might code myself :D

**Comment by Dicebar** [comment]
Glad to help! 👍
